---
title: "Tick Pathogen Report"
output: pdf_document
params:
  report_name: "default_report_name"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(janitor)
library(tidyverse)
library(ggplot2)
library(knitr)
RawResults.dat <- read.csv("2024-05-15 Tick Pathogen PCR Test 6(Results).csv", header = FALSE)
InstrumentInfo.dat <- head(RawResults.dat, n = 45)

Tech <- InstrumentInfo.dat[45,2]
Date <- as.Date(InstrumentInfo.dat[36,2])

```


# Results for `r params$report_name`:

```{r Result Section, echo=FALSE, warning=FALSE}

PCR_Results.dat <- tail(RawResults.dat, n = -46)
PCR_Results.dat <- row_to_names(PCR_Results.dat, row_number = 1)
PCR_Results.dat <- clean_names(PCR_Results.dat)
PCR_Results.dat$ct <- as.numeric(PCR_Results.dat$ct)
PCR_Results.dat$quantity <- as.numeric(PCR_Results.dat$quantity)
PCR_Results.dat$`r_superscript_2` <- as.numeric(PCR_Results.dat$r_superscript_2)
PCR_Results.dat$ct <- ifelse(is.na(PCR_Results.dat$ct), 41, PCR_Results.dat$ct)
PCR_Results.dat=within(PCR_Results.dat,{
  result=NA
  result[ ct<"35"] = "POSITIVE"
  result[ ct>="35"] = "negative"
})

SampleName.dat <- subset(PCR_Results.dat, sample_name == sample)
ResultTable.dat <- select(SampleName.dat, c('target_name', 'result'))
Names <- c("*Anaplasma phagocytophilum*", "*Babesia microti*", "*Borrelia burgdorferi*", "*Borrelia mayonii*", "*Borrelia miyamotoi*", "*Ehrlichia muris eauclarensis*", "Powassan virus", "Extraction Control")
ResultTable.dat$target_name <- Names
kable(ResultTable.dat[1:2], row.names = FALSE)

```

A positive result is not a diagnosis of infection. If you are concerned about illness, you should consult your doctor. 

# Instrument

```{r Import-data, echo=FALSE}
InstrumentInfo.dat <- head(RawResults.dat, n = 45)

Name <- InstrumentInfo.dat[35,2]
Type <- InstrumentInfo.dat[40,2]
SN <- InstrumentInfo.dat[39,2]
ROX <- InstrumentInfo.dat[17,2]
FAM <- InstrumentInfo.dat[9,2]
Background <- InstrumentInfo.dat[3,2]

```

Type: `r Type` 

Serial Number: `r SN`

Dye calibrations:  
FAM: `r FAM`  
ROX: `r ROX`  
Background: `r Background`
