---
title: "Tick Panel Plate QC"
output: pdf_document
params:
  report_name: "default_report_name"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(janitor)
library(dplyr)
library(knitr)

# csv_file <- "USGS-Ticks-qPCR01-altered.csv"
# csv_base_name <- tools::file_path_sans_ext(basename(csv_file))
# sample <- "POS"
# ^ ^ Remove these when the file is called by the QC script ^ ^

RawResults.dat <- read.csv(csv_file, header = FALSE)
#RawResults.dat <- as.data.frame(read_excel(csv_file, sheet = "Results", col_names = FALSE))
InstrumentInfo.dat <- head(RawResults.dat, n = 45)

#report_name <- csv_base_name
Tech <- InstrumentInfo.dat[45,2]
Date <- as.Date(InstrumentInfo.dat[36,2])
```

# QC check for `r params$report_name`:

Positive control results:

```{r Result Section, echo=FALSE, warning=FALSE}

PCR_Results.dat <- tail(RawResults.dat, n = -46)
PCR_Results.dat <- row_to_names(PCR_Results.dat, row_number = 1)
PCR_Results.dat <- clean_names(PCR_Results.dat)
PCR_Results.dat$ct <- as.numeric(PCR_Results.dat$ct)
PCR_Results.dat$quantity <- as.numeric(PCR_Results.dat$quantity)
PCR_Results.dat$`r_superscript_2` <- as.numeric(PCR_Results.dat$r_superscript_2)
PCR_Results.dat$ct <- ifelse(is.na(PCR_Results.dat$ct), 41, PCR_Results.dat$ct)


# Check for at least one positive for each target
# Each target has an empirically determined Ct cutoff that should be changed to reflect the assay as they are updated
# Add a pass_check column with conditions for each target
PCR_Results.dat <- PCR_Results.dat %>%
  mutate(
    pass_check = case_when(
      target_name == "A. phagocytophilum" & ct < 35 & amp_score > 1 & cq_conf > 0.8 ~ "Positive",
      target_name == "B. microti" & ct < 35 & amp_score > 1 & cq_conf > 0.8 ~ "Positive",
      target_name == "B. burgdorferi" & ct < 34 & amp_score > 1 & cq_conf > 0.8 ~ "Positive",
      target_name == "B. mayonii" & ct < 35 & amp_score > 1 & cq_conf > 0.8 ~ "Positive",
      target_name == "B. miyamotoi" & ct < 36 & amp_score > 1 & cq_conf > 0.8 ~ "Positive",
      target_name == "E. muris" & ct < 34 & amp_score > 1 & cq_conf > 0.8 ~ "Positive",
      target_name == "Powassan virus" & ct < 35 & amp_score > 1 & cq_conf > 0.8 ~ "Positive",
      target_name == "Extraction Control" & ct < 36 & amp_score > 1 & cq_conf > 0.8 ~ "Positive",
      target_name == "A. phagocytophilum" & ct < 35 & (amp_score <= 1 | cq_conf <= 0.8) ~ "Inconclusive",
      target_name == "B. microti" & ct < 35 & (amp_score <= 1 | cq_conf <= 0.8) ~ "Inconclusive",
      target_name == "B. burgdorferi" & ct < 34 & (amp_score <= 1 | cq_conf <= 0.8) ~ "Inconclusive",
      target_name == "B. mayonii" & ct < 35 & (amp_score <= 1 | cq_conf <= 0.8) ~ "Inconclusive",
      target_name == "B. miyamotoi" & ct < 36 & (amp_score <= 1 | cq_conf <= 0.8) ~ "Inconclusive",
      target_name == "E. muris" & ct < 34 & (amp_score <= 1 | cq_conf <= 0.8) ~ "Inconclusive",
      target_name == "Powassan virus" & ct < 35 & (amp_score <= 1 | cq_conf <= 0.8) ~ "Inconclusive",
      target_name == "Extraction Control" & ct < 36 & (amp_score <= 1 | cq_conf <= 0.8) ~ "Inconclusive",
      TRUE ~ "Negative"
    )
  )


Anaplasma_check <- PCR_Results.dat[PCR_Results.dat$target_name == "A. phagocytophilum", ]
Ana_pass <- if ("Positive" %in% Anaplasma_check$pass_check) {
  "Positive"
} else if ("Inconclusive" %in% Anaplasma_check$pass_check) {
  "Inconclusive"
} else if (all(Anaplasma_check$pass_check == "Negative")) {
  "Negative"
} else {
  "Unknown"  # Optional fallback
}

Babesia_check <- PCR_Results.dat[PCR_Results.dat$target_name == "B. microti", ]
Babesia_pass <- if ("Positive" %in% Babesia_check$pass_check) {
  "Positive"
} else if ("Inconclusive" %in% Babesia_check$pass_check) {
  "Inconclusive"
} else if (all(Babesia_check$pass_check == "Negative")) {
  "Negative"
} else {
  "Unknown"  # Optional fallback
}

Bburgdorf_check <- PCR_Results.dat[PCR_Results.dat$target_name == "B. burgdorferi", ]
Bburgdorf_pass <- if ("Positive" %in% Bburgdorf_check$pass_check) {
  "Positive"
} else if ("Inconclusive" %in% Bburgdorf_check$pass_check) {
  "Inconclusive"
} else if (all(Bburgdorf_check$pass_check == "Negative")) {
  "Negative"
} else {
  "Unknown"  # Optional fallback
}

Bmayo_check <- PCR_Results.dat[PCR_Results.dat$target_name == "B. mayonii", ]
Bmayo_pass <- if ("Positive" %in% Bmayo_check$pass_check) {
  "Positive"
} else if ("Inconclusive" %in% Bmayo_check$pass_check) {
  "Inconclusive"
} else if (all(Bmayo_check$pass_check == "Negative")) {
  "Negative"
} else {
  "Unknown"  # Optional fallback
}

Bmiya_check <- PCR_Results.dat[PCR_Results.dat$target_name == "B. miyamotoi", ]
Bmiya_pass <- if ("Positive" %in% Bmiya_check$pass_check) {
  "Positive"
} else if ("Inconclusive" %in% Bmiya_check$pass_check) {
  "Inconclusive"
} else if (all(Bmiya_check$pass_check == "Negative")) {
  "Negative"
} else {
  "Unknown"  # Optional fallback
}

Emuris_check <- PCR_Results.dat[PCR_Results.dat$target_name == "E. muris", ]
Emuris_pass <- if ("Positive" %in% Emuris_check$pass_check) {
  "Positive"
} else if ("Inconclusive" %in% Emuris_check$pass_check) {
  "Inconclusive"
} else if (all(Emuris_check$pass_check == "Negative")) {
  "Negative"
} else {
  "Unknown"  # Optional fallback
}

Powassan_check <- PCR_Results.dat[PCR_Results.dat$target_name == "Powassan virus", ]
Powassan_pass <- if ("Positive" %in% Powassan_check$pass_check) {
  "Positive"
} else if ("Inconclusive" %in% Powassan_check$pass_check) {
  "Inconclusive"
} else if (all(Powassan_check$pass_check == "Negative")) {
  "Negative"
} else {
  "Unknown"  # Optional fallback
}

Extraction_check <- PCR_Results.dat[PCR_Results.dat$target_name == "Extraction Control", ]
Extraction_pass <- if ("Positive" %in% Extraction_check$pass_check) {
  "Positive"
} else if ("Inconclusive" %in% Extraction_check$pass_check) {
  "Inconclusive"
} else if (all(Extraction_check$pass_check == "Negative")) {
  "Negative"
} else {
  "Unknown"  # Optional fallback
}

plate_check <- c(Ana_pass, Babesia_pass, Bburgdorf_pass, Bmayo_pass, Bmiya_pass, Emuris_pass, Powassan_pass, Extraction_pass)

# Make a table with the target check
SampleName.dat <- subset(PCR_Results.dat, sample_name == "POS")
ResultTable.dat <- select(SampleName.dat, c('target_name', 'pass_check'))
ResultTable.dat$whole_plate <- plate_check
Names <- c("*Anaplasma phagocytophilum*", "*Babesia microti*", "*Borrelia burgdorferi*", "*Borrelia mayonii*", "*Borrelia miyamotoi*", "*Ehrlichia muris eauclarensis*", "Powassan virus", "Extraction Control")
ResultTable.dat$target_name <- Names
colnames(ResultTable.dat) <- c("Target Name", "Positive Control", "Whole Plate")
ResultTable.dat <- ResultTable.dat %>%
  dplyr::mutate(across(where(is.logical), ~ ifelse(.x, "Positive", "NEGATIVE")))
kable(ResultTable.dat, row.names = FALSE)

```

If any results in this table are negative, that target must be re-run for every sample.

# Samples to re-run

```{r no-amp, echo=FALSE, warning=FALSE, results='asis'}

no_positive_samples <- PCR_Results.dat %>%
  group_by(sample_name) %>%
  dplyr::summarise(All_False = all(pass_check == FALSE)) %>%
  filter(All_False) %>%
  pull(sample_name)
no_positive_samples <- setdiff(no_positive_samples, "NTC")
no_positive_samples <- paste0('* ', no_positive_samples, '\n')
cat(no_positive_samples)
```

These samples had no amplification for any target. They need to be re-run.

# Instrument

```{r Instrument-data, echo=FALSE}
InstrumentInfo.dat <- head(RawResults.dat, n = 45)

Name <- InstrumentInfo.dat[35,2]
Type <- InstrumentInfo.dat[40,2]
SN <- InstrumentInfo.dat[39,2]
ROX <- InstrumentInfo.dat[17,2]
FAM <- InstrumentInfo.dat[9,2]
Background <- InstrumentInfo.dat[3,2]

```

Type: `r Type` 

Serial Number: `r SN`

Dye calibrations:  
FAM: `r FAM`  
ROX: `r ROX`  
Background: `r Background`
